/**
 * Example E2E tests showing how to use the seed helper.
 *
 * Prerequisites:
 *   1. Generate e2e/fixtures/seed.json (see e2e/fixtures/README.md)
 *   2. Start the dev server: pnpm dev
 *   3. Run: pnpm e2e
 */
import { test, expect } from '@playwright/test'
import { seedAndLoad } from './helpers/seed'
// @ts-expect-error — fixture file is generated by the user; will error until created
import fixture from './fixtures/seed.json'

test.describe('dashboard smoke tests', () => {
  test.beforeEach(async ({ page }) => {
    await seedAndLoad(page, fixture)
  })

  test('scatter plot renders with activities', async ({ page }) => {
    // Scatter is the default view
    await expect(page.locator('svg circle.vis-unselected, svg circle.vis-selected').first()).toBeVisible()
  })

  test('activity count shows in filter panel', async ({ page }) => {
    // Filter panel header shows "N / M" with N ≥ 1
    const countText = page.locator('text=/\\d+ \\/ \\d+/')
    await expect(countText).toBeVisible()
    const text = await countText.textContent()
    const match = text?.match(/(\d+) \/ (\d+)/)
    expect(Number(match?.[1])).toBeGreaterThan(0)
  })

  test('sport filter shows Run selected by default', async ({ page }) => {
    // Default filter includes Run sport type
    const sportSummary = page.locator('details summary span').first()
    await expect(sportSummary).toContainText(/Run|All sports/)
  })
})
