/**
 * US16: Quick date and distance range presets
 */
import { test, expect } from '@playwright/test'
import { seedAndLoad } from './helpers/seed'
// @ts-expect-error — fixture file is generated by the user; will error until created
import fixture from './fixtures/seed.json'

test.describe('filter quick-select presets (US16)', () => {
  test.beforeEach(async ({ page }) => {
    await seedAndLoad(page, fixture)
  })

  test('date preset buttons are visible: 6 mo, 1 yr, 2 yr, All', async ({ page }) => {
    await expect(page.getByRole('button', { name: '6 mo' })).toBeVisible()
    await expect(page.getByRole('button', { name: '1 yr' })).toBeVisible()
    await expect(page.getByRole('button', { name: '2 yr' })).toBeVisible()
    await expect(page.getByRole('button', { name: 'All' })).toBeVisible()
  })

  test('clicking "1 yr" sets from-date to one year ago', async ({ page }) => {
    await page.getByRole('button', { name: '1 yr' }).click()
    await page.waitForTimeout(300)

    // The active preset should be highlighted (orange background)
    await expect(page.getByRole('button', { name: '1 yr' })).toHaveClass(/bg-orange-500/)

    // The other presets should not be active
    await expect(page.getByRole('button', { name: '6 mo' })).not.toHaveClass(/bg-orange-500/)
    await expect(page.getByRole('button', { name: '2 yr' })).not.toHaveClass(/bg-orange-500/)
    await expect(page.getByRole('button', { name: 'All' })).not.toHaveClass(/bg-orange-500/)
  })

  test('clicking "All" resets date range to full data extent', async ({ page }) => {
    // First apply a preset to create a non-null dateRange
    await page.getByRole('button', { name: '6 mo' }).click()
    await page.waitForTimeout(200)
    await expect(page.getByRole('button', { name: '6 mo' })).toHaveClass(/bg-orange-500/)

    // Now click All
    await page.getByRole('button', { name: 'All' }).click()
    await page.waitForTimeout(200)
    await expect(page.getByRole('button', { name: 'All' })).toHaveClass(/bg-orange-500/)
    // The other presets should not be active
    await expect(page.getByRole('button', { name: '6 mo' })).not.toHaveClass(/bg-orange-500/)
  })

  test('distance preset buttons are visible and activate correctly', async ({ page }) => {
    const tenKBtn = page.getByRole('button', { name: '< 10k' })
    const marathonBtn = page.getByRole('button', { name: '< Marathon' })
    await expect(tenKBtn).toBeVisible()
    await expect(marathonBtn).toBeVisible()

    await tenKBtn.click()
    await page.waitForTimeout(200)
    await expect(tenKBtn).toHaveClass(/bg-orange-500/)
    await expect(marathonBtn).not.toHaveClass(/bg-orange-500/)

    await marathonBtn.click()
    await page.waitForTimeout(200)
    await expect(marathonBtn).toHaveClass(/bg-orange-500/)
    await expect(tenKBtn).not.toHaveClass(/bg-orange-500/)
  })

  test('manually adjusting slider deselects active date preset', async ({ page }) => {
    // Activate a preset first
    await page.getByRole('button', { name: '1 yr' }).click()
    await page.waitForTimeout(200)
    await expect(page.getByRole('button', { name: '1 yr' })).toHaveClass(/bg-orange-500/)

    // Move the date range slider by changing the min text input
    const fromInput = page.locator('.space-y-5 input[type="date"]').first()
    const count = await fromInput.count()
    if (count > 0) {
      await fromInput.fill('2010-01-01')
      await fromInput.press('Enter')
      await page.waitForTimeout(200)
      // After manual change, no preset should be active
      await expect(page.getByRole('button', { name: '1 yr' })).not.toHaveClass(/bg-orange-500/)
    } else {
      // If the slider uses range inputs instead of date inputs, just check presets are still visible
      await expect(page.getByRole('button', { name: '1 yr' })).toBeVisible()
    }
  })
})
