/**
 * US10: Tileable and tabbable layout
 */
import { test, expect } from '@playwright/test'
import { seedAndLoad } from './helpers/seed'
// @ts-expect-error — fixture file is generated by the user
import fixture from './fixtures/seed.json'

/**
 * In Double/Quad mode each panel has its own tab strip containing "Scatter" buttons.
 * Single mode has no such buttons inside main (the view buttons are in the header instead).
 * Count of main > button[name=Scatter] = number of visible panels in Double/Quad.
 */
const panelScatterBtns = (page: import('@playwright/test').Page) =>
  page.locator('main').getByRole('button', { name: 'Scatter', exact: true })

test.describe('layout manager (US10)', () => {
  test.beforeEach(async ({ page }) => {
    await seedAndLoad(page, fixture)
    await page.evaluate(() => localStorage.removeItem('dash:workspaceState'))
    await page.reload()
    await page.waitForSelector('svg circle', { timeout: 10000 })
  })

  test('AC1 — Single/Double/Quad controls are present in the top bar', async ({ page }) => {
    const header = page.locator('header')
    await expect(header.getByRole('button', { name: 'Single', exact: true })).toBeVisible()
    await expect(header.getByRole('button', { name: 'Double', exact: true })).toBeVisible()
    await expect(header.getByRole('button', { name: 'Quad', exact: true })).toBeVisible()
  })

  test('AC1 — Single mode shows view type selector in the top bar', async ({ page }) => {
    const header = page.locator('header')
    await expect(header.getByRole('button', { name: 'Scatter', exact: true })).toBeVisible()
    await expect(header.getByRole('button', { name: 'Series', exact: true })).toBeVisible()
    await expect(header.getByRole('button', { name: 'Map', exact: true })).toBeVisible()
    await expect(header.getByRole('button', { name: 'Table', exact: true })).toBeVisible()
    await expect(panelScatterBtns(page)).toHaveCount(0)
  })

  test('AC2 — Double mode renders two panels each with a view type tab strip', async ({ page }) => {
    await page.getByRole('button', { name: 'Double', exact: true }).click()
    await page.waitForTimeout(300)
    await expect(panelScatterBtns(page)).toHaveCount(2)
  })

  test('AC2 — Quad mode renders four panels each with a view type tab strip', async ({ page }) => {
    await page.getByRole('button', { name: 'Quad', exact: true }).click()
    await page.waitForTimeout(300)
    await expect(panelScatterBtns(page)).toHaveCount(4)
  })

  test('AC3 — Double mode uses a two-column CSS grid (responsive reflow)', async ({ page }) => {
    await page.getByRole('button', { name: 'Double', exact: true }).click()
    await page.waitForTimeout(300)
    await expect(page.locator('main')).toHaveClass(/grid-cols-2/)
  })

  test('AC3 — Quad mode uses a two-column CSS grid', async ({ page }) => {
    await page.getByRole('button', { name: 'Quad', exact: true }).click()
    await page.waitForTimeout(300)
    await expect(page.locator('main')).toHaveClass(/grid-cols-2/)
  })

  test('AC4 — layout mode persists across page reload', async ({ page }) => {
    await page.getByRole('button', { name: 'Double', exact: true }).click()
    await page.waitForTimeout(300)
    await page.reload()
    await page.waitForSelector('svg circle', { timeout: 10000 })
    await page.waitForTimeout(300)
    await expect(panelScatterBtns(page)).toHaveCount(2)
  })

  test('AC4 — slot view type persists across page reload', async ({ page }) => {
    await page.getByRole('button', { name: 'Double', exact: true }).click()
    await page.waitForTimeout(300)
    const tableBtns = page.locator('main').getByRole('button', { name: 'Table', exact: true })
    await tableBtns.last().click()
    await page.waitForTimeout(300)
    await page.reload()
    await page.waitForSelector('svg circle', { timeout: 10000 })
    await page.waitForTimeout(300)
    await expect(page.locator('main table')).toBeVisible()
  })

  test('AC5 — filter updates apply to all visible panels simultaneously', async ({ page }) => {
    await page.getByRole('button', { name: 'Double', exact: true }).click()
    await page.waitForTimeout(300)
    const tableBtns = page.locator('main').getByRole('button', { name: 'Table', exact: true })
    await tableBtns.last().click()
    await page.waitForTimeout(500)
    const rowsBefore = await page.locator('main table tbody tr').count()
    await page.locator('aside').getByRole('button', { name: '< 10k' }).click()
    await page.waitForTimeout(500)
    const rowsAfter = await page.locator('main table tbody tr').count()
    expect(rowsAfter).toBeLessThan(rowsBefore)
  })
})
