/**
 * US20: Axis-constrained zoom on scatter plot
 *
 * These tests filter activities to a small set so the scatter plot is sparse
 * enough for the D3 brush overlay to receive drag events (dense hit circles
 * from thousands of dots can block the overlay).
 */
import { test, expect } from '@playwright/test'
import { seedAndLoad } from './helpers/seed'
// @ts-expect-error — fixture file is generated by the user; will error until created
import fixture from './fixtures/seed.json'

/** Locate the scatter plot SVG specifically (avoids tiny icon SVGs). */
const scatterSvg = (page: import('@playwright/test').Page) =>
  page.locator('[data-testid="scatter-svg"]')

/** Read tick text from the x-axis group inside the scatter SVG. */
async function readXTicks(page: import('@playwright/test').Page): Promise<string[]> {
  return page.evaluate(() => {
    const svg = document.querySelector('[data-testid="scatter-svg"]')!
    const mainG = svg.querySelector(':scope > g')!
    const children = Array.from(mainG.children).filter(c => c.tagName === 'g')
    const xAxisG = children.find(
      (c, i) => i >= 2 && !c.classList.contains('grid-x') && !c.classList.contains('grid-y') && !c.classList.contains('brush')
    )
    if (!xAxisG) return []
    return Array.from(xAxisG.querySelectorAll('.tick text')).map(t => t.textContent ?? '').filter(Boolean)
  })
}

/** Read tick text from the y-axis group inside the scatter SVG. */
async function readYTicks(page: import('@playwright/test').Page): Promise<string[]> {
  return page.evaluate(() => {
    const svg = document.querySelector('[data-testid="scatter-svg"]')!
    const mainG = svg.querySelector(':scope > g')!
    const children = Array.from(mainG.children).filter(c => c.tagName === 'g')
    let count = 0
    for (const c of children) {
      if (c.classList.contains('grid-x') || c.classList.contains('grid-y') || c.classList.contains('brush')) continue
      count++
      if (count === 2) {
        return Array.from(c.querySelectorAll('.tick text')).map(t => t.textContent ?? '').filter(Boolean)
      }
    }
    return []
  })
}

/** Apply a narrow distance filter to produce a sparse scatter plot. */
async function filterToSparse(page: import('@playwright/test').Page) {
  // Click "< 10k" preset to filter to short runs
  await page.getByRole('button', { name: '< 10k' }).click()
  await page.waitForTimeout(300)
  // Click "6 mo" date preset to filter recent runs
  await page.getByRole('button', { name: '6 mo' }).click()
  await page.waitForTimeout(500)
}

test.describe('scatter axis-constrained zoom (US20)', () => {
  test.beforeEach(async ({ page }) => {
    await seedAndLoad(page, fixture)
    await expect(scatterSvg(page)).toBeAttached()
    await page.waitForTimeout(500)
  })

  test('brush-to-zoom is available for all axis combinations', async ({ page }) => {
    // Default axes: X=distance, Y=average_pace
    await expect(page.locator('[data-testid="scatter-svg"] .brush .overlay')).toBeAttached()

    // Switch to X=elapsed_time — brush should still be present
    const xSelect = page.locator('select').first()
    await xSelect.selectOption('elapsed_time')
    await page.waitForTimeout(500)
    await expect(page.locator('[data-testid="scatter-svg"] .brush .overlay')).toBeAttached()

    // Switch to Y=distance (non-pace) — brush should still be present
    const ySelect = page.locator('select').nth(1)
    await ySelect.selectOption('distance')
    await page.waitForTimeout(500)
    await expect(page.locator('[data-testid="scatter-svg"] .brush .overlay')).toBeAttached()
  })

  test('horizontal drag zooms only x-axis (y unchanged)', async ({ page }) => {
    await filterToSparse(page)
    const svg = scatterSvg(page)
    const box = await svg.boundingBox()
    expect(box).toBeTruthy()

    const xBefore = await readXTicks(page)
    const yBefore = await readYTicks(page)
    expect(xBefore.length).toBeGreaterThan(0)
    expect(yBefore.length).toBeGreaterThan(0)

    // Horizontal drag — barely any vertical movement → x-constrained
    const startX = box!.x + box!.width * 0.3
    const y = box!.y + box!.height * 0.5
    const endX = box!.x + box!.width * 0.7

    await page.mouse.move(startX, y)
    await page.mouse.down()
    await page.mouse.move(endX, y + 2, { steps: 10 })
    await page.mouse.up()
    await page.waitForTimeout(500)

    const xAfter = await readXTicks(page)
    const yAfter = await readYTicks(page)

    // X ticks should have changed (zoomed in)
    expect(JSON.stringify(xAfter)).not.toEqual(JSON.stringify(xBefore))
    // Y ticks should be unchanged (x-only zoom)
    expect(yAfter).toEqual(yBefore)
  })

  test('vertical drag zooms only y-axis (x unchanged)', async ({ page }) => {
    await filterToSparse(page)
    const svg = scatterSvg(page)
    const box = await svg.boundingBox()
    expect(box).toBeTruthy()

    const xBefore = await readXTicks(page)
    const yBefore = await readYTicks(page)
    expect(xBefore.length).toBeGreaterThan(0)
    expect(yBefore.length).toBeGreaterThan(0)

    // Vertical drag — barely any horizontal movement → y-constrained
    const x = box!.x + box!.width * 0.5
    const startY = box!.y + box!.height * 0.3
    const endY = box!.y + box!.height * 0.7

    await page.mouse.move(x, startY)
    await page.mouse.down()
    await page.mouse.move(x + 2, endY, { steps: 10 })
    await page.mouse.up()
    await page.waitForTimeout(500)

    const xAfter = await readXTicks(page)
    const yAfter = await readYTicks(page)

    // Y ticks should have changed (zoomed in)
    expect(JSON.stringify(yAfter)).not.toEqual(JSON.stringify(yBefore))
    // X ticks should be unchanged (y-only zoom)
    expect(xAfter).toEqual(xBefore)
  })

  test('diagonal drag zooms both axes', async ({ page }) => {
    await filterToSparse(page)
    const svg = scatterSvg(page)
    const box = await svg.boundingBox()
    expect(box).toBeTruthy()

    const xBefore = await readXTicks(page)
    const yBefore = await readYTicks(page)

    // Diagonal drag — both axes should change
    const startX = box!.x + box!.width * 0.3
    const startY = box!.y + box!.height * 0.3
    const endX = box!.x + box!.width * 0.7
    const endY = box!.y + box!.height * 0.7

    await page.mouse.move(startX, startY)
    await page.mouse.down()
    await page.mouse.move(endX, endY, { steps: 10 })
    await page.mouse.up()
    await page.waitForTimeout(500)

    const xAfter = await readXTicks(page)
    const yAfter = await readYTicks(page)

    const xChanged = JSON.stringify(xAfter) !== JSON.stringify(xBefore)
    const yChanged = JSON.stringify(yAfter) !== JSON.stringify(yBefore)
    expect(xChanged || yChanged).toBeTruthy()
  })

  test('double-click resets both axes after single-axis zoom', async ({ page }) => {
    await filterToSparse(page)
    const svg = scatterSvg(page)
    const box = await svg.boundingBox()
    expect(box).toBeTruthy()

    const xBefore = await readXTicks(page)

    // Horizontal drag to zoom x only
    const startX = box!.x + box!.width * 0.35
    const y = box!.y + box!.height * 0.5
    const endX = box!.x + box!.width * 0.65

    await page.mouse.move(startX, y)
    await page.mouse.down()
    await page.mouse.move(endX, y + 1, { steps: 10 })
    await page.mouse.up()
    await page.waitForTimeout(500)

    // X ticks should have changed
    const xZoomed = await readXTicks(page)
    expect(JSON.stringify(xZoomed)).not.toEqual(JSON.stringify(xBefore))

    // Double-click the plot to reset
    await svg.dblclick({ position: { x: box!.width / 2, y: box!.height / 2 } })
    await page.waitForTimeout(500)

    // After reset, plot should re-render
    await expect(page.locator('[data-testid="scatter-svg"] circle').first()).toBeAttached()
  })

  test('autoscale button resets after single-axis zoom', async ({ page }) => {
    await filterToSparse(page)
    const svg = scatterSvg(page)
    const box = await svg.boundingBox()
    expect(box).toBeTruthy()

    // Vertical drag to zoom y only
    const x = box!.x + box!.width * 0.5
    const startY = box!.y + box!.height * 0.35
    const endY = box!.y + box!.height * 0.65

    await page.mouse.move(x, startY)
    await page.mouse.down()
    await page.mouse.move(x + 1, endY, { steps: 10 })
    await page.mouse.up()
    await page.waitForTimeout(500)

    // Click auto-scale button (force: true bypasses any overlay)
    const autoScaleBtn = page.getByRole('button', { name: /auto.?scale/i })
    await autoScaleBtn.click({ force: true })
    await page.waitForTimeout(500)

    // Plot should render after auto-scale
    await expect(page.locator('[data-testid="scatter-svg"] circle').first()).toBeAttached()
  })
})
