/**
 * US19: Series plot defaults and manual autoscale
 */
import { test, expect } from '@playwright/test'
import { seedAndLoad } from './helpers/seed'
// @ts-expect-error — fixture file is generated by the user; will error until created
import fixture from './fixtures/seed.json'

test.describe('series plot defaults (US19)', () => {
  test.beforeEach(async ({ page }) => {
    await seedAndLoad(page, fixture)
    // Add the first activity to the roster (needed for series plot to render controls)
    const firstHit = page.locator('svg circle.hit-unselected').first()
    await expect(firstHit).toBeAttached()
    await firstHit.click({ force: true })
    await page.waitForTimeout(300)
    // Switch to the Series tab
    await page.getByRole('button', { name: 'Series', exact: true }).click()
    await page.waitForTimeout(800)
  })

  test('default y-metric is Cumulative Pace and time mode is Moving', async ({ page }) => {
    // y-metric buttons: 'cumul.' is orange when active
    const cumulBtn = page.getByRole('button', { name: 'cumul.' })
    await expect(cumulBtn).toHaveClass(/bg-orange-500/)

    // time mode buttons: 'moving' is orange when active
    const movingBtn = page.getByRole('button', { name: 'moving' })
    await expect(movingBtn).toHaveClass(/bg-orange-500/)
  })

  test('autoscale button is visible', async ({ page }) => {
    const autoscaleBtn = page.getByRole('button', { name: /auto.?scale/i })
    await expect(autoscaleBtn).toBeVisible()
  })

  test('switching y-metric does not reset y-axis when domain is already set', async ({ page }) => {
    // Switch from cumulative → rolling via button click
    const rollingBtn = page.getByRole('button', { name: 'rolling' })
    await rollingBtn.click()
    await page.waitForTimeout(300)
    await expect(rollingBtn).toHaveClass(/bg-orange-500/)
    // Plot should still be rendered (at least one path in the SVG)
    await expect(page.locator('svg path').first()).toBeAttached()
  })

  test('switching time mode does not reset y-axis', async ({ page }) => {
    const elapsedBtn = page.getByRole('button', { name: 'elapsed' })
    await elapsedBtn.click()
    await page.waitForTimeout(300)
    await expect(elapsedBtn).toHaveClass(/bg-orange-500/)
    await expect(page.locator('svg path').first()).toBeAttached()
  })

  test('clicking autoscale button re-fits the y-axis', async ({ page }) => {
    const autoscaleBtn = page.getByRole('button', { name: /auto.?scale/i })
    await autoscaleBtn.click()
    await page.waitForTimeout(300)
    // Plot should still render after autoscale
    await expect(page.locator('svg path').first()).toBeAttached()
  })
})
