/**
 * US22: Improved scatter plot tooltip
 */
import { test, expect } from '@playwright/test'
import { seedAndLoad } from './helpers/seed'
// @ts-expect-error — fixture file is generated by the user; will error until created
import fixture from './fixtures/seed.json'

test.describe('scatter tooltip (US22)', () => {
  test.beforeEach(async ({ page }) => {
    await seedAndLoad(page, fixture)
  })

  test('tooltip shows full name, readable date, distance and pace on hover', async ({ page }) => {
    // Hover the first visible scatter dot (hit area, r=12, class hit-unselected or hit-selected)
    const firstHit = page.locator('svg circle.hit-unselected, svg circle.hit-selected').first()
    await expect(firstHit).toBeAttached()
    await firstHit.hover({ force: true })

    const tooltip = page.locator('.pointer-events-none.bg-white')
    await expect(tooltip).toBeVisible()

    const html = await tooltip.innerHTML()
    // Full name: the <p> must exist with text (not necessarily truncated)
    const nameEl = tooltip.locator('p').first()
    await expect(nameEl).toBeVisible()
    const name = await nameEl.textContent()
    expect(name?.length).toBeGreaterThan(0)

    // Date format: should match "D Mon YYYY" like "8 Mar 2026"
    await expect(tooltip).toContainText(/\d{1,2} [A-Z][a-z]{2} \d{4}/)

    // Distance: should contain "km"
    await expect(tooltip).toContainText(/km/)

    // Pace: should contain "/km"
    await expect(tooltip).toContainText(/\/km/)

    console.log('Tooltip HTML:', html)
  })

  test('tooltip omits age/age-grade when athlete has no date of birth', async ({ page }) => {
    // Check whether the fixture athlete has a dateOfBirth.
    // If they don't, verify age/age-grade lines don't appear.
    const athleteDob = (fixture as { athlete?: { dateOfBirth?: string } }).athlete?.dateOfBirth

    if (!athleteDob) {
      const firstHit = page.locator('svg circle.hit-unselected, svg circle.hit-selected').first()
      await firstHit.hover({ force: true })
      const tooltip = page.locator('.pointer-events-none.bg-white')
      await expect(tooltip).toBeVisible()
      await expect(tooltip).not.toContainText(/Age:/)
      await expect(tooltip).not.toContainText(/Age grade:/)
    } else {
      // Athlete has DOB — age and age-grade should appear
      const firstHit = page.locator('svg circle.hit-unselected, svg circle.hit-selected').first()
      await firstHit.hover({ force: true })
      const tooltip = page.locator('.pointer-events-none.bg-white')
      await expect(tooltip).toBeVisible()
      await expect(tooltip).toContainText(/Age: \d+/)
      await expect(tooltip).toContainText(/Age grade: \d+\.\d+%/)
    }
  })
})
